on:
  issue_comment:
    types: [created]

jobs:
  command:
    if: |-
      ${{ startswith(github.event.comment.body, '/') && !contains(github.event.comment.body, '
      ') }}
    runs-on: self-hosted
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            var cmd = context.payload.comment.body.substring(1);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Invoked ' + cmd
            });
